# CCTV Person Detection Dataset configuration
path: dataset/merged_cctv_person  # dataset root dir
train: images/train  # train images (relative to path)
val: images/val      # val images (relative to path)

# Classes
names:
  0: person
